#!/bin/bash

VERSION='0.0.1'
BUILD='fedora-10-i386'

# Remove junk
find src/ -type f -regex \.*.py[co] -delete

# Build tar.gz
cp -r src funcshell-$VERSION
tar -czf funcshell-$VERSION.tar.gz funcshell-$VERSION/
rm -fr funcshell-$VERSION
mv funcshell-$VERSION.tar.gz ~/rpmbuild/SOURCES/

# Build srpm
rm ~/rpmbuild/SRPMS/funcshell-$VERSION-*.src.rpm
rpmbuild -bs --nodeps funcshell.spec

# Build rpm
mock -vr $BUILD ~/rpmbuild/SRPMS/funcshell-$VERSION-*.src.rpm

# Check for issues
rpmlint /var/lib/mock/$BUILD/result/funcshell-$VERSION-*.rpm
